# Generated by Django 4.0.1 on 2022-02-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='category',
        ),
    ]
